### ISSUE TITLE
Downloading raw data files in batches

### ISSUE THREAD

**Issue by Xinzhao1990** [MetaSUB/metasub_utils#6]
* MetaSUB Utilities version: 0.4.1
* Python version: 3.6.0
* Operating System: macOS 10.14.1

### What I Did

Hi David

Thank you for your time and help. Metasub utils v0.4.1 is working

However, all the samples of a city would be randomly downloaded once the city name is specified. It is not feasible for cities with big datasets (such as Hong Kong/NYC/London), and we cannot work on the files until the entire dataset is downloaded, since the forward and reverse read files are not downloaded consecutively. Also, if the connection is interrupted mid-download, the previously downloaded samples would have to be overwritten and downloaded all over again. 

Therefore, would it be possible to provide an option where we can specify the (list of) files/samples that we can download in one go? This way, anyone can download in smaller sample batches to avoid the above issues. 

Thank you very much. As always, we appreciate your kind help.

Regards

**Comment by dcdanko** [comment]
In v0.5.0 (just published) you can download files by sample name. Let me know if there's any issue.

v0.4.1 does kick off downloads of paired files at the same time but they might not be finished at the same time due to multithreading. Since overall performance is more important than order here I'm not going to change that behavior (and hopefully it won't be necessary with download by sample name).

**Comment by Xinzhao1990** [comment]
Hi David,

I installed metasub_utils (v0.5.0). 

Since the new version does not have --sample_name flag, I just entered Sample_ID/uuid/ha_id (I don't know which one I should enter here) to specify the sample name. However, the sample specified here was not in wasabi download list, instead, a lot of unrelated samples were included. 

Besides, I also noticed that some of the previously downloaded files (specified with flag --city_name) are not matched to our metadata. These samples started with haib17CEM5106 or haib18CEM5332 in uuids, while all HK samples should have the same prefix haib18CEM5453. Given this, we are worrying that some of HK sample would be incorrectly deposited in other cities' directories. 

Therefore, could you please add a flag where we can specify the uuids? Through this, we could download samples corresponding to the metadata and avoid downloading files that are not in our list. 

Again, I truly appreciate your time and help.

Best regards

**Comment by dcdanko** [comment]
My mistake, `v0.5.3` fixes the missing flag.

You are not correct that all Hong Kong samples come from `haib18CEM5453`. We have Hong Kong samples from air sampling, CSD*, and pilot all sequenced separately. In general it is not the case that a single city was sequenced all at once.

However I suspect you mean that you just want CSD* samples. In `0.5.3` I  have added a flag to filter by project name as well as city.
